dubbo:
  application:
    # 这个部分定义了应用的名字，值为dubbo-springboot-demo-consumer。
    name: dubbo-springboot-demo-consumer
  protocol:
    # 这个部分定义了使用的协议，这里使用的是Dubbo协议
    name: dubbo
    # port字段的值设为-1表示使用注册中心定义的端口
    port: 8003
  registry:
    # 定义了注册中心的地址
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
server:
  port: 8082
